In [1]:
which python

SyntaxError: invalid syntax (<ipython-input-1-d8603f9f9bc3>, line 1)

In [2]:
np.array(10)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [5]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#for float numbers

In [8]:
np.linspace(1, 2, 6)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [9]:
np.random.rand(3)

array([0.8350128 , 0.42421596, 0.77423497])

In [11]:
np.random.rand(3,2)

array([[0.19136371, 0.28754654],
       [0.54347719, 0.78947807],
       [0.41474103, 0.31864909]])

In [20]:
my_list = np.random.rand(1000)

In [21]:
# slicing always gives a view not a copy

In [22]:
my_list[:]

array([2.33274100e-01, 8.27323804e-01, 4.48168798e-01, 4.11103949e-01,
       2.45402767e-01, 8.01538765e-01, 5.94835874e-01, 8.52016388e-01,
       5.84971354e-01, 3.49677749e-01, 2.96096659e-01, 6.64937178e-01,
       7.06222596e-01, 3.04883091e-01, 3.11562284e-01, 4.50793862e-01,
       6.39608972e-01, 5.58218411e-01, 1.25905136e-01, 7.86661130e-01,
       8.36768667e-01, 2.65271768e-01, 3.18041032e-01, 8.58269229e-01,
       6.10158912e-01, 3.46406323e-01, 7.33689266e-01, 7.73169819e-01,
       3.98233302e-01, 3.69728030e-01, 7.90661584e-02, 4.56737770e-01,
       8.74458014e-02, 3.26585457e-01, 3.46043347e-01, 8.07806526e-01,
       9.66406655e-01, 7.98715501e-01, 5.49595369e-01, 3.28919920e-01,
       2.29364226e-01, 6.90073853e-02, 8.53492046e-01, 4.57640401e-01,
       8.84127999e-01, 7.77737408e-01, 4.76005000e-01, 5.52343734e-01,
       6.64103463e-01, 2.05301649e-01, 6.57283907e-01, 8.93228630e-01,
       2.56062208e-01, 2.49716117e-01, 6.16728168e-01, 2.66290285e-01,
      

In [23]:
#making changes in my_list

In [24]:
_[0] = 0

In [25]:
my_list

array([0.00000000e+00, 8.27323804e-01, 4.48168798e-01, 4.11103949e-01,
       2.45402767e-01, 8.01538765e-01, 5.94835874e-01, 8.52016388e-01,
       5.84971354e-01, 3.49677749e-01, 2.96096659e-01, 6.64937178e-01,
       7.06222596e-01, 3.04883091e-01, 3.11562284e-01, 4.50793862e-01,
       6.39608972e-01, 5.58218411e-01, 1.25905136e-01, 7.86661130e-01,
       8.36768667e-01, 2.65271768e-01, 3.18041032e-01, 8.58269229e-01,
       6.10158912e-01, 3.46406323e-01, 7.33689266e-01, 7.73169819e-01,
       3.98233302e-01, 3.69728030e-01, 7.90661584e-02, 4.56737770e-01,
       8.74458014e-02, 3.26585457e-01, 3.46043347e-01, 8.07806526e-01,
       9.66406655e-01, 7.98715501e-01, 5.49595369e-01, 3.28919920e-01,
       2.29364226e-01, 6.90073853e-02, 8.53492046e-01, 4.57640401e-01,
       8.84127999e-01, 7.77737408e-01, 4.76005000e-01, 5.52343734e-01,
       6.64103463e-01, 2.05301649e-01, 6.57283907e-01, 8.93228630e-01,
       2.56062208e-01, 2.49716117e-01, 6.16728168e-01, 2.66290285e-01,
      

In [26]:
len(my_list[0:100]) #to grab 100 item

100

In [27]:
len(my_list[0:100:2]) # to grab from those 100 items,it get half of 100

50

In [28]:
#multi dimension

In [29]:
multi = np.random.rand(5,5)

In [30]:
multi[:3, :2]

array([[0.4460353 , 0.62333529],
       [0.19362357, 0.18236158],
       [0.47499608, 0.54110049]])

In [31]:
why numpy instead of array?

Object `array` not found.


In [33]:
#why numpy instead of array?

In [34]:
#to down caste data type

In [36]:
floattype = np.linspace(1, 2, 6)

In [38]:
floattype

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [39]:
float_to_int = floattype.astype(np.int64)

In [40]:
float_to_int

array([1, 1, 1, 1, 1, 2], dtype=int64)

In [41]:
int_to_float = float_to_int.astype(np.float64)

In [42]:
int_to_float

array([1., 1., 1., 1., 1., 2.])

In [43]:
#an example for linear algebra

In [44]:
#[apple,google,microsoft]
bob = np.array([1000, 1000, 1000])
alice = np.array([500, 2000, 500])
porfolios = np.array([bob, alice])

In [45]:
porfolios

array([[1000, 1000, 1000],
       [ 500, 2000,  500]])

In [49]:
changes = np.array([[1.2, 0, 0], #apple's stock incre by 20%
                   [0, 0.95, 0], #google decreased by 5%
                   [0, 0, 1],#same for microsoft
                   [0.2, -0.05, 0]#total stock change
                   ] )

In [51]:
np.matmul(changes, porfolios)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [52]:
porfolios.transpose().shape

(3, 2)

In [74]:
np.matmul(changes, porfolios.transpose()).transpose()

array([[ 1.20000000e+03,  9.50000000e+02,  1.00000000e+03,
         1.50000000e+02],
       [ 6.00000000e+02,  1.90000000e+03,  5.00000000e+02,
        -5.55111512e-15]])

In [75]:
_.int32

AttributeError: 'numpy.ndarray' object has no attribute 'int32'

In [55]:
_.dtype

dtype('float64')

In [72]:
_53.int

AttributeError: 'numpy.ndarray' object has no attribute 'int'

In [57]:
#finding determinant and inverse

In [68]:
t = np.ones([3,3])

In [69]:
t

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
np.linalg.det(t)

0.0

In [71]:
np.linalg.inv(t)

LinAlgError: Singular matrix

In [76]:
np.linalg.eigvals(t)

array([-2.22044605e-16,  3.00000000e+00,  0.00000000e+00])

In [77]:
np.linalg.eig(t)

(array([-2.22044605e-16,  3.00000000e+00,  0.00000000e+00]),
 array([[-0.81649658,  0.57735027,  0.        ],
        [ 0.40824829,  0.57735027, -0.70710678],
        [ 0.40824829,  0.57735027,  0.70710678]]))

In [80]:
np.histogram(t)

(array([0, 0, 0, 0, 0, 9, 0, 0, 0, 0], dtype=int64),
 array([0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5]))

In [87]:
r = np.random.rand(3)

In [88]:
r

array([0.32395403, 0.98251516, 0.80322506])

In [92]:
t = np.random.rand(3)

In [93]:
t

array([0.38230088, 0.16180339, 0.67283506])

In [94]:
np.histogram(t,bins)

NameError: name 'bins' is not defined

In [97]:
import matplotlib as plt

In [99]:
plt.hist(t)

AttributeError: module 'matplotlib' has no attribute 'pyplot'

In [102]:
t = np.random.rand(4,3,2)

In [103]:
t

array([[[0.06551231, 0.75345163],
        [0.59766872, 0.20124174],
        [0.76941974, 0.15010093]],

       [[0.37659514, 0.86238211],
        [0.45807759, 0.01714919],
        [0.46975011, 0.04497378]],

       [[0.01214341, 0.89411972],
        [0.88452914, 0.98731064],
        [0.55101719, 0.56522801]],

       [[0.79210369, 0.50223564],
        [0.85253307, 0.24782199],
        [0.92282049, 0.71804233]]])

In [104]:
t.mean(axis = 0)

array([[0.31158863, 0.75304727],
       [0.69820213, 0.36338089],
       [0.67825188, 0.36958626]])

In [106]:
t.mean(axis=2)

array([[0.40948197, 0.39945523, 0.45976033],
       [0.61948862, 0.23761339, 0.25736194],
       [0.45313156, 0.93591989, 0.5581226 ],
       [0.64716966, 0.55017753, 0.82043141]])

In [107]:
nan_array = np.array((np.nan, 1, 2, np.nan))

In [108]:
nan_array.sum()

nan

In [110]:
np.nansum(nan_array) #without nan value

3.0

In [111]:
#don't do
import scipy
#do this
from scipy import optimize